# Generated by Django 3.2.6 on 2021-08-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piloto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subject',
            field=models.CharField(help_text='Email subject', max_length=200),
        ),
    ]
